// Code generated by timoni.
// Note that this file must have no imports and all values must be concrete.

package main

// Defaults
values: {
	message: "Hello World"
	image: {
		repository: "cgr.dev/chainguard/nginx"
		digest:     "sha256:d2b0e52d7c2e5dd9fe5266b163e14d41ed97fd380deb55a36ff17efd145549cd"
		tag:        "1.25.1"
	}
}
