// Code generated by timoni. DO NOT EDIT.
// Note that this file must have no imports and all values must be concrete.

package main

values: {
	image: {
		repository: "cgr.dev/chainguard/redis"
		tag:        "7.2.1"
		digest:     "sha256:31e5ad71a315a1d6b75a93dfabcbfbe2cfcd6fe295cb605bad7441c17a2c48e8"
	}
}
