// Code generated by timoni. DO NOT EDIT.
// Note that this file is required and should export
// a stream of Kubernetes objects under the timoni.objects field.

package main

import (
	templates "timoni.sh/test/templates"
)

// Define the schema for the user-supplied values.
// At runtime, Timoni injects the supplied values
// and validates them according to the Config schema.
values: templates.#Config

// Define the instance that outputs the Kubernetes resources.
// At runtime, Timoni builds the instance and validates
// the resulting resources according to their Kubernetes schema.
instance: templates.#Instance & {
	// The user-supplied values are merged with the
	// default values at runtime by Timoni.
	config: values
	// The instance name and namespace tag values
	// are injected at runtime by Timoni.
	config: metadata: {
		name:      string @tag(name)
		namespace: string @tag(namespace)
	}
}

// Expose the instance build result for Timoni's runtime.
timoni: {
	objects: [ for obj in instance.objects {obj}]
}
