name: e2e

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read

defaults:
  run:
    working-directory: test

jobs:
  kubernetes:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:3
        ports:
          - 5555:5000
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Setup staging cluster
        uses: helm/kind-action@06c1ae10762d3b9c1644e7fe69596ae519e015a2 # v1.15.0
        with:
          cluster_name: timoni-staging
      - name: Setup production cluster
        uses: helm/kind-action@06c1ae10762d3b9c1644e7fe69596ae519e015a2 # v1.15.0
        with:
          cluster_name: timoni-production
      - name: Build
        working-directory: ${{ github.workspace }}
        run: make build
      - name: Push modules
        run: make push
      - name: Deploy
        run: make fleet-deploy
      - name: Check
        run: make fleet-deploy-check
      - name: Uninstall
        run: make fleet-deploy-uninstall
